#!/bin/bash
     
case "$1" in
   start)
      echo "Starting RPI Power service"
      python /userdata/system/scripts/python/relay.py &
   ;;
   stop)
      echo "TODO: stop service"
   ;;
   status)
      echo "TODO: print status"
   ;;
esac
